using JuMP, HiGHS, Printf, Dates, TOML

include("model.jl")

format_num(x) = @sprintf("%.6f", isapprox(x, 0.0; atol=1e-9) ? 0.0 : x)

function write_results_csv(path, load, gensets, battery, u, y, Pg, SFOC, lambda, P_ch, P_dis, E)
    max_breakpoints = maximum(length(g.SFOC) for g in gensets)

    open(path, "w") do io
        header = ["timestep", "generator", "load_kw", "u", "startup",
                  "Pg_kw", "sfoc_gkwh", "fuel_gph", "load_pct",
                  "P_ch_kw", "P_dis_kw", "E_kwh", "soc_pct"]
        append!(header, ["lambda_$(i)" for i in 1:max_breakpoints])
        println(io, join(header, ","))

        for t in eachindex(load), g in eachindex(gensets)
            pg_val  = value(Pg[g, t])
            fg_val  = value(SFOC[g, t])
            pg_val  = isapprox(pg_val, 0.0; atol=1e-9) ? 0.0 : pg_val
            fg_val  = isapprox(fg_val, 0.0; atol=1e-9) ? 0.0 : fg_val
            fuel    = fg_val * pg_val          # g/h  (sfoc × power)
            loadpct = pg_val / gensets[g].P_max * 100.0  # % of rated capacity

            # Battery values (same for all generators in a timestep)
            pch_val  = isapprox(value(P_ch[t]), 0.0; atol=1e-9) ? 0.0 : value(P_ch[t])
            pdis_val = isapprox(value(P_dis[t]), 0.0; atol=1e-9) ? 0.0 : value(P_dis[t])
            e_val    = value(E[t])
            soc_val  = e_val / battery.E_max * 100.0

            row = [
                string(t),
                string(g),
                @sprintf("%.1f", load[t]),
                value(u[g, t]) > 0.5 ? "1" : "0",
                value(y[g, t]) > 0.5 ? "1" : "0",   # startup event
                format_num(pg_val),
                format_num(fg_val),
                format_num(fuel),
                @sprintf("%.2f", loadpct),
                format_num(pch_val),
                format_num(pdis_val),
                format_num(e_val),
                @sprintf("%.2f", soc_val),
            ]

            for i in 1:max_breakpoints
                if i <= length(gensets[g].SFOC)
                    push!(row, format_num(value(lambda[g, t, i])))
                else
                    push!(row, "")
                end
            end

            println(io, join(row, ","))
        end
    end
end

function main()
    # ── Run identity ───────────────────────────────────────────────────────────
    # Set run_label before each run — it becomes part of the folder name.
    # Fill run_desc with a short note about what you're testing (optional).
    run_label = ""
    run_desc  = ""
    git_hash  = strip(read(`git rev-parse HEAD`, String))
    git_dirty = !success(`git diff --quiet HEAD`)

    gensets = [
        (P_max=385.0, P_min=0.5*385, P = [0.5*385, 0.75*385, 310, 385], SFOC = [193,191,191,198], startup_cost = 15000.0),  # g fuel equivalent per start
        (P_max=385.0, P_min=0.5*385, P = [0.5*385, 0.75*385, 310, 385], SFOC = [193,191,191,198], startup_cost = 15000.0)
    ]

    # ── Timestep duration ──────────────────────────────────────────────────────
    # Must match RESAMPLE_MINUTES in data/preprocess.py
    dt_minutes = 15
    dt = dt_minutes / 60.0   # hours

    battery = (
        E_max     = 940.0,    # kWh  total battery capacity
        SOC_min   = 0.2,      #      minimum state of charge
        SOC_max   = 0.9,      #      maximum state of charge
        P_ch_max  = 753.25,   # kW   nominal max charging power (655V*1150A)
        P_dis_max = 943.2,    # kW   nominal max discharging power (655V*1440A)
        eta_ch    = 0.95,     #      charging efficiency
        eta_dis   = 0.95,     #      discharging efficiency
        E_init    = 0.5*940,  # kWh  initial stored energy (50% SOC)
        dt        = dt,       # h    timestep duration
    )

    # ── Load profile from operational data ────────────────────────────────────
    # Generated by data/preprocess.py from data/v01.csv
    load = Float64[]
    open(joinpath(@__DIR__, "data", "load_profile.csv")) do io
        readline(io)  # skip header: timestep,load_kw,datetime
        for line in eachline(io)
            parts = split(line, ",")
            push!(load, parse(Float64, parts[2]))
        end
    end

    show_solver_log = true

    model, u, y, Pg, SFOC, lambda, P_ch, P_dis, E = build_model(gensets, load, battery)

    if !show_solver_log
        set_silent(model)
    end

    optimize!(model)

    if termination_status(model) == OPTIMAL
        # ── Create run directory ───────────────────────────────────────────────
        timestamp = Dates.format(now(), "yyyy-mm-dd_HHMMSS")
        run_dir   = joinpath(@__DIR__, "runs", "$(timestamp)_$(run_label)")
        mkpath(run_dir)

        # ── Write params.toml ──────────────────────────────────────────────────
        params_dict = Dict(
            "run" => Dict(
                "date"        => Dates.format(now(), "yyyy-mm-dd"),
                "label"       => run_label,
                "description" => run_desc,
                "git_hash"    => git_hash,
                "git_dirty"   => git_dirty,
            ),
            "solver" => Dict(
                "status"       => string(termination_status(model)),
                "objective"    => objective_value(model),
                "solve_time_s" => solve_time(model),
            ),
            "battery" => Dict(
                "E_max"       => battery.E_max,
                "SOC_min"     => battery.SOC_min,
                "SOC_max"     => battery.SOC_max,
                "P_ch_max"    => battery.P_ch_max,
                "P_dis_max"   => battery.P_dis_max,
                "eta_ch"      => battery.eta_ch,
                "eta_dis"     => battery.eta_dis,
                "E_init"      => battery.E_init,
                "dt"          => battery.dt,
            ),
            "generators" => [
                Dict(
                    "P_max"        => g.P_max,
                    "P_min"        => g.P_min,
                    "P"            => collect(Float64, g.P),
                    "SFOC"         => collect(Float64, g.SFOC),
                    "startup_cost" => g.startup_cost,
                )
                for g in gensets
            ],
        )
        open(joinpath(run_dir, "params.toml"), "w") do io
            TOML.print(io, params_dict)
        end

        # ── Write results CSV ──────────────────────────────────────────────────
        csv_path = joinpath(run_dir, "dispatch_results.csv")
        write_results_csv(csv_path, load, gensets, battery, u, y, Pg, SFOC, lambda, P_ch, P_dis, E)

        # Write .current_run so report.qmd picks it up without env vars
        open(joinpath(@__DIR__, ".current_run"), "w") do io
            write(io, run_dir)
        end

        println("Objective value = ", @sprintf("%.2f", objective_value(model)))
        println("Solve time      = ", @sprintf("%.2f", solve_time(model)), " s")
        println("Run saved to    → ", run_dir)
    else
        println("Model not solved to optimality.")
        println("  Termination status: ", termination_status(model))
        println("  Primal status:      ", primal_status(model))
    end
end

main()